/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


package my.topic2;
import java.util.*;
/**
 *
 * @author mahit
 */
public class Negative extends javax.swing.JFrame {
    Result negResult;
    String[] negAnswer = {"53.6", "All of the Above", "true", "false"};
    
    /**
     * Creates new form Info
     */
    public Negative(Result result2) {
        initComponents();
        negResult = result2;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelInfoNegative = new javax.swing.JPanel();
        jButtonInfo = new javax.swing.JButton();
        jLabelInfo = new javax.swing.JLabel();
        jScrollPaneIPositive = new javax.swing.JScrollPane();
        jTextAreaPositive = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jPanelQuizNegative = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jComboBox5 = new javax.swing.JComboBox<>();
        jComboBox6 = new javax.swing.JComboBox<>();
        jQuestion7 = new javax.swing.JLabel();
        jQuestion8 = new javax.swing.JLabel();
        jQuestion9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanelInfoNegative.setBackground(new java.awt.Color(204, 255, 204));
        jPanelInfoNegative.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 0), 5, true));

        jButtonInfo.setBackground(new java.awt.Color(124, 239, 245));
        jButtonInfo.setText("Next");
        jButtonInfo.setBorder(new javax.swing.border.MatteBorder(null));
        jButtonInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInfoActionPerformed(evt);
            }
        });

        jLabelInfo.setFont(new java.awt.Font("OCR A Extended", 0, 24)); // NOI18N
        jLabelInfo.setText("Negative");

        jTextAreaPositive.setEditable(false);
        jTextAreaPositive.setBackground(new java.awt.Color(225, 255, 225));
        jTextAreaPositive.setColumns(20);
        jTextAreaPositive.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jTextAreaPositive.setRows(5);
        jTextAreaPositive.setTabSize(2);
        jTextAreaPositive.setText("Pollution of discarded technologies...\n\t- taints drinking water and farm land\n\t- disrupts aqutic environments\nIn 2020, 53.6 million tons of e-waste being created globally\n\n\nMinerals, such as silver, have to be mined\n\t- Depleting resources and damaging the environment\n\t- Concerns for the miners' health\n\n\nIncreased use of technology can lead to...\n\t- Eye strain\t\t\t\t\t\t\t\t\t\t \t\t\t- Headaches\n\t- Altered sleeping patterns\t\t\t- Feeling isolated\n\t- Back pain\n");
        jScrollPaneIPositive.setViewportView(jTextAreaPositive);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/topic2/ewaste1.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanelInfoNegativeLayout = new javax.swing.GroupLayout(jPanelInfoNegative);
        jPanelInfoNegative.setLayout(jPanelInfoNegativeLayout);
        jPanelInfoNegativeLayout.setHorizontalGroup(
            jPanelInfoNegativeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInfoNegativeLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanelInfoNegativeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelInfoNegativeLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))
                    .addGroup(jPanelInfoNegativeLayout.createSequentialGroup()
                        .addGroup(jPanelInfoNegativeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelInfo)
                            .addGroup(jPanelInfoNegativeLayout.createSequentialGroup()
                                .addComponent(jScrollPaneIPositive, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(21, Short.MAX_VALUE))))
        );
        jPanelInfoNegativeLayout.setVerticalGroup(
            jPanelInfoNegativeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInfoNegativeLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabelInfo)
                .addGap(18, 18, 18)
                .addGroup(jPanelInfoNegativeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelInfoNegativeLayout.createSequentialGroup()
                        .addGap(0, 10, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(35, 35, 35)
                        .addComponent(jButtonInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPaneIPositive))
                .addGap(16, 16, 16))
        );

        getContentPane().add(jPanelInfoNegative, "card2");

        jPanelQuizNegative.setBackground(new java.awt.Color(210, 239, 250));
        jPanelQuizNegative.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 0), 5, true));

        jLabel4.setFont(new java.awt.Font("OCR A Extended", 0, 24)); // NOI18N
        jLabel4.setText("Quiz");

        jButton4.setBackground(new java.awt.Color(204, 255, 204));
        jButton4.setText("Submit");
        jButton4.setBorder(new javax.swing.border.MatteBorder(null));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Back Pain", "Eye Strain", "Headaches", "All of the Above" }));
        jComboBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox5ActionPerformed(evt);
            }
        });

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "true", "false" }));

        jQuestion7.setText("How many tons of e-waste did the world produce in 2020?");

        jQuestion8.setText("Increased use of technology can lead to...");

        jQuestion9.setText("True or False: The process of mining can damage the natural environment.");

        jLabel2.setText("True or False: E-Waste does not negatively affect farm land.");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "true", "false" }));

        javax.swing.GroupLayout jPanelQuizNegativeLayout = new javax.swing.GroupLayout(jPanelQuizNegative);
        jPanelQuizNegative.setLayout(jPanelQuizNegativeLayout);
        jPanelQuizNegativeLayout.setHorizontalGroup(
            jPanelQuizNegativeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelQuizNegativeLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
            .addGroup(jPanelQuizNegativeLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanelQuizNegativeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelQuizNegativeLayout.createSequentialGroup()
                        .addGroup(jPanelQuizNegativeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jQuestion7, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(82, Short.MAX_VALUE))
                    .addGroup(jPanelQuizNegativeLayout.createSequentialGroup()
                        .addGroup(jPanelQuizNegativeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jQuestion9)
                            .addComponent(jQuestion8, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanelQuizNegativeLayout.createSequentialGroup()
                .addGroup(jPanelQuizNegativeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelQuizNegativeLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelQuizNegativeLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelQuizNegativeLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelQuizNegativeLayout.setVerticalGroup(
            jPanelQuizNegativeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelQuizNegativeLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel4)
                .addGap(28, 28, 28)
                .addComponent(jQuestion7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jQuestion8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jQuestion9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addGroup(jPanelQuizNegativeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelQuizNegativeLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addGroup(jPanelQuizNegativeLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        getContentPane().add(jPanelQuizNegative, "card4");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInfoActionPerformed
        jPanelInfoNegative.setVisible(false);
        jPanelQuizNegative.setVisible(true);
    }//GEN-LAST:event_jButtonInfoActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String[] negResponse = {jTextField2.getText(), jComboBox5.getSelectedItem().toString(), jComboBox6.getSelectedItem().toString()};
        negResult.markQuiz(negResponse, negAnswer);
        Action infoAct = new Action(negResult);
        infoAct.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jComboBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
        
    }
    
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButtonInfo;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelInfo;
    private javax.swing.JPanel jPanelInfoNegative;
    private javax.swing.JPanel jPanelQuizNegative;
    private javax.swing.JLabel jQuestion7;
    private javax.swing.JLabel jQuestion8;
    private javax.swing.JLabel jQuestion9;
    private javax.swing.JScrollPane jScrollPaneIPositive;
    private javax.swing.JTextArea jTextAreaPositive;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables

}
