/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package my.topic2;

/**
 *
 * @author mahit
 */
public class Positive extends javax.swing.JFrame {
    Result posResult;
    String[] posAnswer = {"online", "satellite", "true"};
    
    /**
     * Creates new form Info
     */
    public Positive(Result result1) {
        initComponents();
        posResult = result1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelInfoPositive = new javax.swing.JPanel();
        jButtonInfo = new javax.swing.JButton();
        jLabelInfo = new javax.swing.JLabel();
        jScrollPaneIPositive = new javax.swing.JScrollPane();
        jTextAreaPositive = new javax.swing.JTextArea();
        jPanelPositive = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jTextFieldPos1 = new javax.swing.JTextField();
        jComboBoxPos3 = new javax.swing.JComboBox<>();
        jQuestion7 = new javax.swing.JLabel();
        jQuestion8 = new javax.swing.JLabel();
        jQuestion9 = new javax.swing.JLabel();
        jTextFieldPos2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanelInfoPositive.setBackground(new java.awt.Color(204, 255, 204));
        jPanelInfoPositive.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 0), 5, true));

        jButtonInfo.setBackground(new java.awt.Color(124, 239, 245));
        jButtonInfo.setText("Next");
        jButtonInfo.setBorder(new javax.swing.border.MatteBorder(null));
        jButtonInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInfoActionPerformed(evt);
            }
        });

        jLabelInfo.setFont(new java.awt.Font("OCR A Extended", 0, 24)); // NOI18N
        jLabelInfo.setText("Positive");

        jTextAreaPositive.setEditable(false);
        jTextAreaPositive.setBackground(new java.awt.Color(225, 255, 225));
        jTextAreaPositive.setColumns(20);
        jTextAreaPositive.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextAreaPositive.setRows(5);
        jTextAreaPositive.setText("Technology allows online appointments.\nTechnology is also used to help our body function through \ndevices, such as the pacemaker.\nKeeping track of health levels (ex. diabetes)\nMRI, X-Ray \n\nSensors, such as the MethaneSAT satellite (used to track methane \nemissions), are used to track and predict our environmental state.\nElectric Vehicle\n");
        jScrollPaneIPositive.setViewportView(jTextAreaPositive);

        javax.swing.GroupLayout jPanelInfoPositiveLayout = new javax.swing.GroupLayout(jPanelInfoPositive);
        jPanelInfoPositive.setLayout(jPanelInfoPositiveLayout);
        jPanelInfoPositiveLayout.setHorizontalGroup(
            jPanelInfoPositiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInfoPositiveLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
            .addGroup(jPanelInfoPositiveLayout.createSequentialGroup()
                .addGroup(jPanelInfoPositiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelInfoPositiveLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabelInfo))
                    .addGroup(jPanelInfoPositiveLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jScrollPaneIPositive, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanelInfoPositiveLayout.setVerticalGroup(
            jPanelInfoPositiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInfoPositiveLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabelInfo)
                .addGap(31, 31, 31)
                .addComponent(jScrollPaneIPositive, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(jButtonInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        getContentPane().add(jPanelInfoPositive, "card2");

        jPanelPositive.setBackground(new java.awt.Color(210, 239, 250));
        jPanelPositive.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 0), 5, true));

        jLabel4.setFont(new java.awt.Font("OCR A Extended", 0, 24)); // NOI18N
        jLabel4.setText("Quiz");

        jButton4.setBackground(new java.awt.Color(204, 255, 204));
        jButton4.setText("Submit");
        jButton4.setBorder(new javax.swing.border.MatteBorder(null));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTextFieldPos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPos1ActionPerformed(evt);
            }
        });

        jComboBoxPos3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "true", "false" }));

        jQuestion7.setText("Fill In The Blank: Technology allows for _________ appointments, making healthcare more accessible.");

        jQuestion8.setText("Fill In The Blank: The MethaneSAT is a ___________ used to track methane emissons.");

        jQuestion9.setText("True or False: Technology allows for more environmentally-friendly transportation.");

        javax.swing.GroupLayout jPanelPositiveLayout = new javax.swing.GroupLayout(jPanelPositive);
        jPanelPositive.setLayout(jPanelPositiveLayout);
        jPanelPositiveLayout.setHorizontalGroup(
            jPanelPositiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPositiveLayout.createSequentialGroup()
                .addGroup(jPanelPositiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelPositiveLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanelPositiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelPositiveLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 466, Short.MAX_VALUE))
                            .addGroup(jPanelPositiveLayout.createSequentialGroup()
                                .addGroup(jPanelPositiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jQuestion9)
                                    .addComponent(jQuestion8, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jQuestion7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelPositiveLayout.createSequentialGroup()
                        .addGap(262, 476, Short.MAX_VALUE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19))
            .addGroup(jPanelPositiveLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jComboBoxPos3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanelPositiveLayout.createSequentialGroup()
                .addGroup(jPanelPositiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPositiveLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jTextFieldPos1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelPositiveLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jTextFieldPos2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelPositiveLayout.setVerticalGroup(
            jPanelPositiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPositiveLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel4)
                .addGap(28, 28, 28)
                .addComponent(jQuestion7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldPos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jQuestion8)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldPos2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jQuestion9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBoxPos3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        getContentPane().add(jPanelPositive, "card4");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInfoActionPerformed
        jPanelInfoPositive.setVisible(false);
        jPanelPositive.setVisible(true);
        
    }//GEN-LAST:event_jButtonInfoActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String[] posResponse = {jTextFieldPos1.getText(), jTextFieldPos2.getText(), jComboBoxPos3.getSelectedItem().toString()};
        posResult.markQuiz(posResponse, posAnswer);
        Negative infoNeg = new Negative(posResult);
        infoNeg.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextFieldPos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPos1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPos1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                
            }
        });
        
    }
    
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButtonInfo;
    private javax.swing.JComboBox<String> jComboBoxPos3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelInfo;
    private javax.swing.JPanel jPanelInfoPositive;
    private javax.swing.JPanel jPanelPositive;
    private javax.swing.JLabel jQuestion7;
    private javax.swing.JLabel jQuestion8;
    private javax.swing.JLabel jQuestion9;
    private javax.swing.JScrollPane jScrollPaneIPositive;
    private javax.swing.JTextArea jTextAreaPositive;
    private javax.swing.JTextField jTextFieldPos1;
    private javax.swing.JTextField jTextFieldPos2;
    // End of variables declaration//GEN-END:variables

}
